### ISSUE TITLE
performance gap

### ISSUE THREAD

**Issue by yangzhch6** [rajasekharmekala/echoprompt#1]
I do not change your code and run:

> python main.py --model-name gpt-3.5-turbo --dataset gsm8k --learning_mode cot_rephrase_v1 --max_tokens 450

I only get a result of 75.1%, which is inconsistent with your paper's performance (83.5%) in Table 9.

> correct_count:  991   
> total_count:  1320   
> accuracy:  0.7507575757575757  

Is there anything wrong with your code?
Looking for your reply, thank you!

**Comment by yangzhch6** [comment]
Besides that,
when running:

> python main.py --model-name gpt-3.5-turbo --dataset gsm8k --learning_mode cot --max_tokens --max_tokens 300

I only get a result of 72.9%, which is inconsistent with your paper's performance (75.1%) in Table 9.
> correct_count:  962
> total_count:  1320
> accuracy:  0.7287878787878788

**Comment by rajasekharmekala** [comment]
Hi ZhiCheng Yang,

Sorry for the late reply, Somehow your email ended up in my spam.

Coming to your question, GSM8K is a much more complex task to solve and it
requires longer chain-of-thought generation. Also, the model we used for
evaluation is the March variant, gpt-3.5-turbo-0301 averaged over 3
iterations.

Please try with the following commands

python main.py --model-name gpt-3.5-turbo-0301 --dataset gsm8k
--learning_mode cot --max_tokens 450
python main.py --model-name gpt-3.5-turbo-0301 --dataset gsm8k
--learning_mode cot_rephrase_v1 --max_tokens 600

Even after this, there might be 1-2% discrepancy in the values reported in
the paper and the values obtained with this code, for this particular model.
This is because the model is fine-tuned for chat applications and hence it
did not follow the exact answer extraction format that we specified (we
have mentioned this in the paper). On human evaluation of the logs, we
found that a few more questions were accurately answered, but missed our
answer extraction code.

Note that we did not face such issues with other models
Some examples are provided below (I am omitting the 8 exemplars in each
prompt for simplicity):

Q: Alex, Stan, and Adelwolfe are trying to catch them all, Pokemon that is.
Together they have caught 339 Pokemon. Alex has caught 5 more than Stan,
and Stan has caught 13 less than 4 times as many as Adelwolfe has caught.
How many Pokemon has Stan caught?
A:
2023-10-17 11:15:34 INFO
subq:
2023-10-17 11:15:34 INFO golden_answer: 147
2023-10-17 11:15:34 INFO prediction: FALSE
2023-10-17 11:15:34 INFO The final answer: rewriting in simple words, the
question is: "given that alex, stan, and adelwolfe have caught a total of
339 pokemon, and alex has caught 5 more than stan, and stan has caught 13
less than 4 times as many as adelwolfe has caught, how many pokemon has
stan caught?"
now, to answer the rewritten question, let's use variables to represent the
number of pokemon each person has caught. let x be the number of pokemon
adelwolfe has caught. then, according to the problem, stan has caught 4x -
13, and alex has caught 5 more than stan, which is (4x - 13) + 5 = 4x - 8.
together, they have caught 339 pokemon, so we can write an equation:
x + (4x - 13) + (4x - 8) = 339
simplifying the left side, we get:
9x - 21 = 339
adding 21 to both sides, we get:
9x = 360
dividing both sides by 9, we get:
x = 40
so adelwolfe has caught 40 pokemon. then, we can use the expressions we
found earlier to find out how many pokemon stan and alex have caught:
stan = 4x - 13 = 4(40) - 13 = 147
alex = 4x - 8 = 4(40) - 8 = 152
therefore, stan has caught 147 pokemon

Q: Mrs. Cruz is looking for a house that will not go beyond her $400 000
budget. She saw a property that has a selling price of $350 000. On top of
that, the buyer has to pay a brokerage fee which is 5% of the selling
price, and also the transfer fee that is 12% of the selling price. How much
more is the total price of the house than Mrs. Cruz's budget?
A:
2023-10-17 11:16:16 INFO
subq:
2023-10-17 11:16:16 INFO golden_answer: 9500
2023-10-17 11:16:16 INFO prediction: FALSE
2023-10-17 11:16:16 INFO The final answer: $9 500
2023-10-17 11:16:16 INFO The full answer:Rewriting in simple words, the
question is: "Given that Mrs. Cruz has a budget of $400 000 and saw a
property with a selling price of $350 000, but with additional fees of 5%
for brokerage and 12% for transfer, how much more is the total price of the
house than Mrs. Cruz's budget?"
Now, to answer the rewritten question, The brokerage fee is 5% of $350 000,
which is $17 500. The transfer fee is 12% of $350 000, which is $42 000. So
the total additional fees are $17 500 + $42 000 = $59 500. Adding this to
the selling price of $350 000 gives a total price of $409 500. Since Mrs.
Cruz's budget is $400 000, the house is $9 500 more than her budget. The
answer is $9 500.


Q: Sophia and Rose went together to the market to buy onions and potatoes.
Rose bought 4 times the number of onions and potatoes Sophia bought. If
Rose bought 12 onions and 4 potatoes, how many onions and potatoes in total
did Sophia buy at the market?
A:
2023-10-17 11:15:56 INFO
subq:
2023-10-17 11:15:56 INFO golden_answer: 4
2023-10-17 11:15:56 INFO prediction: FALSE
2023-10-17 11:15:56 INFO The final answer: 3 onions and 1 potato
2023-10-17 11:15:56 INFO The full answer:Rewriting in simple words, the
question is: "Given that Rose bought 4 times the number of onions and
potatoes that Sophia bought, and Rose bought 12 onions and 4 potatoes, how
many onions and potatoes in total did Sophia buy at the market?"
Now, to answer the rewritten question, If Rose bought 12 onions, then
Sophia must have bought 12/4 = 3 onions. If Rose bought 4 potatoes, then
Sophia must have bought 4/4 = 1 potato. So Sophia bought 3 onions and 1
potato in total. The answer is 3 onions and 1 potato.

Q: Olivia uploaded 72 pictures to Facebook. She put the same number of the
pics into 8 albums. 3 of the albums were selfies only and 2 of the albums
were portraits. How many portraits and selfies did she have?
A:
2023-10-17 11:16:01 INFO
subq:
2023-10-17 11:16:01 INFO golden_answer: 45
2023-10-17 11:16:01 INFO prediction: FALSE
2023-10-17 11:16:01 INFO The final answer: 27 selfies and 18 portraits

I will update these issues on the ReadMe immediately. Please let me know,
if you have any further questions.


Thanks,
Rajasekhar

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/17/23,
11:55:02 AM

**Comment by rajasekharmekala** [comment]
Hi ZhiCheng Yang,

Sorry for the late reply, Somehow your email ended up in my spam.

Coming to your question, GSM8K is a much more complex task to solve and it requires longer chain-of-thought generation. Also, the model we used for evaluation is the March variant, gpt-3.5-turbo-0301 averaged over 3 iterations.

Please try with the following commands

python main.py --model-name gpt-3.5-turbo-0301 --dataset gsm8k --learning_mode cot --max_tokens 450
python main.py --model-name gpt-3.5-turbo-0301 --dataset gsm8k --learning_mode cot_rephrase_v1 --max_tokens 600

Even after this, there might be 1-2% discrepancy in the values reported in the paper and the values obtained with this code, for this particular model.
This is because the model is fine-tuned for chat applications and hence it did not follow the exact answer extraction format that we specified (we have mentioned this in the paper). On human evaluation of the logs, we found that a few more questions were accurately answered, but missed our answer extraction code.

Note that we did not face such issues with other models
Some examples are provided below (I am omitting the 8 exemplars in each prompt for simplicity):

```
Q: Alex, Stan, and Adelwolfe are trying to catch them all, Pokemon that is.  Together they have caught 339 Pokemon.  Alex has caught 5 more than Stan, and Stan has caught 13 less than 4 times as many as Adelwolfe has caught. How many Pokemon has Stan caught?
A:
2023-10-17 11:15:34 INFO     
subq: 
2023-10-17 11:15:34 INFO     golden_answer: 147
2023-10-17 11:15:34 INFO     prediction: FALSE
2023-10-17 11:15:34 INFO     The final answer: rewriting in simple words, the question is: "given that alex, stan, and adelwolfe have caught a total of 339 pokemon, and alex has caught 5 more than stan, and stan has caught 13 less than 4 times as many as adelwolfe has caught, how many pokemon has stan caught?"
now, to answer the rewritten question, let's use variables to represent the number of pokemon each person has caught. let x be the number of pokemon adelwolfe has caught. then, according to the problem, stan has caught 4x - 13, and alex has caught 5 more than stan, which is (4x - 13) + 5 = 4x - 8. together, they have caught 339 pokemon, so we can write an equation:
x + (4x - 13) + (4x - 8) = 339
simplifying the left side, we get:
9x - 21 = 339
adding 21 to both sides, we get:
9x = 360
dividing both sides by 9, we get:
x = 40
so adelwolfe has caught 40 pokemon. then, we can use the expressions we found earlier to find out how many pokemon stan and alex have caught:
stan = 4x - 13 = 4(40) - 13 = 147
alex = 4x - 8 = 4(40) - 8 = 152
therefore, stan has caught 147 pokemon
```

```
Q: Mrs. Cruz is looking for a house that will not go beyond her $400 000 budget. She saw a property that has a selling price of $350 000. On top of that, the buyer has to pay a brokerage fee which is 5% of the selling price, and also the transfer fee that is 12% of the selling price. How much more is the total price of the house than Mrs. Cruz's budget?
A:
2023-10-17 11:16:16 INFO     
subq: 
2023-10-17 11:16:16 INFO     golden_answer: 9500
2023-10-17 11:16:16 INFO     prediction: FALSE
2023-10-17 11:16:16 INFO     The final answer: $9 500
2023-10-17 11:16:16 INFO     The full answer:Rewriting in simple words, the question is: "Given that Mrs. Cruz has a budget of $400 000 and saw a property with a selling price of $350 000, but with additional fees of 5% for brokerage and 12% for transfer, how much more is the total price of the house than Mrs. Cruz's budget?"
Now, to answer the rewritten question, The brokerage fee is 5% of $350 000, which is $17 500. The transfer fee is 12% of $350 000, which is $42 000. So the total additional fees are $17 500 + $42 000 = $59 500. Adding this to the selling price of $350 000 gives a total price of $409 500. Since Mrs. Cruz's budget is $400 000, the house is $9 500 more than her budget. The answer is $9 500.
```

```
Q: Sophia and Rose went together to the market to buy onions and potatoes. Rose bought 4 times the number of onions and potatoes Sophia bought. If Rose bought 12 onions and 4 potatoes, how many onions and potatoes in total did Sophia buy at the market?
A:
2023-10-17 11:15:56 INFO     
subq: 
2023-10-17 11:15:56 INFO     golden_answer: 4
2023-10-17 11:15:56 INFO     prediction: FALSE
2023-10-17 11:15:56 INFO     The final answer: 3 onions and 1 potato
2023-10-17 11:15:56 INFO     The full answer:Rewriting in simple words, the question is: "Given that Rose bought 4 times the number of onions and potatoes that Sophia bought, and Rose bought 12 onions and 4 potatoes, how many onions and potatoes in total did Sophia buy at the market?"
Now, to answer the rewritten question, If Rose bought 12 onions, then Sophia must have bought 12/4 = 3 onions. If Rose bought 4 potatoes, then Sophia must have bought 4/4 = 1 potato. So Sophia bought 3 onions and 1 potato in total. The answer is 3 onions and 1 potato.
```

```
Q: Olivia uploaded 72 pictures to Facebook.  She put the same number of the pics into 8 albums.  3 of the albums were selfies only and 2 of the albums were portraits.  How many portraits and selfies did she have?
A:
2023-10-17 11:16:01 INFO     
subq: 
2023-10-17 11:16:01 INFO     golden_answer: 45
2023-10-17 11:16:01 INFO     prediction: FALSE
2023-10-17 11:16:01 INFO     The final answer: 27 selfies and 18 portraits
```
I will update these issues on the ReadMe immediately

**Comment by yangzhch6** [comment]
Thank you for your reply.

What does the "iteration" mean?  It seems to be a Self-Consistency experiment.
My understanding is that you set the **epoch** in main.py to 3 and the **temperature** to 0.7

**Comment by rajasekharmekala** [comment]
No, I tried some experiments with multiple epochs and the temperature to 0.7, but all our experiments in the paper are greedy decoding. I just left that as it is, to tryout such other experiments...

There is a slight performance variance even with greedy decoding on the OpenAI apis. not sure why...

**Comment by yangzhch6** [comment]
Thank you for answer my questions.
